name: visual_subs
description: Lets you view subtitles of a video in scrolling format.
publish_to: "none"

version: 1.5.1-beta

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  subtitle: ^0.1.0
  file_picker: ^6.0.0
  provider: ^6.0.5
  dart_casing: ^3.0.1
  gradient_borders: ^1.0.0
  window_manager: ^0.3.6
  flex_color_picker: ^3.3.0
  gap: ^3.0.1
  shared_preferences: ^2.2.2
  media_kit: ^1.1.10+1
  media_kit_libs_audio: ^1.0.4
  media_kit_libs_android_audio: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/default_colors.json
  fonts:
    - family: Verdana
      fonts:
        - asset: fonts/verdana.ttf
        - asset: fonts/verdana-bold.ttf
          weight: 700
        - asset: fonts/verdana-bold-italic.ttf
          weight: 700
          style: italic
    - family: Arial
      fonts:
        - asset: fonts/Arial.ttf
        - asset: fonts/Arial-Italic.ttf
          style: italic
        - asset: fonts/Arial-Light.ttf
          weight: 300
        - asset: fonts/Arial-Light-Italic.ttf
          weight: 300
          style: italic
        - asset: fonts/Arial-Medium.ttf
          weight: 500
        - asset: fonts/Arial-Medium-Italic.ttf
          weight: 500
          style: italic
        - asset: fonts/Arial-Bold.ttf
          weight: 700
        - asset: fonts/Arial-Bold-Italic.ttf
          weight: 700
          style: italic
        - asset: fonts/Arial-Black.ttf
          weight: 900
        - asset: fonts/Arial-Black-Italic.ttf
          weight: 900
          style: italic
